server:
  port: 9191

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_CONSOLE_CLIENT_ID>
            client-secret: <GOOGLE_CONSOLE_SECRET>
          
          
